### PR TITLE
Use : separator for fail counters in Redis

### PR DESCRIPTION
**Pull request by locriandev**
Related with https://github.com/openshift-eng/art-tools/pull/61

### CODE REVIEW

**Comment by thegreyd** [comment]
I don't know how we want to merge this since old keys still have values != 0 in them - like 4.9 - 4.7 right now at https://redis-ui-redis.apps.artc2023.pc3z.p1.openshiftapps.com/

**Comment by locriandev** [comment]
/unhold

Created counters by hand

**Pull request merged**
