### PR TITLE
Doozer: Remove functional_tests

### PR DESCRIPTION
**Pull request by vfreex**
Those tests are already broken and replaced by tests under `tests_functional`

### CODE REVIEW

**Comment by Ximinhan** [comment]
there is a test failed on `doozer/tests/test_distgit/test_rpm_distgit.py::TestRPMDistGit::test_resolve_specfile_async`

**Comment by vfreex** [comment]
@Ximinhan doesn't seem the failed test related to this PR. I am going to open another one for the fix.

**Comment by vfreex** [comment]
https://github.com/openshift-eng/art-tools/pull/873

**Review by locriandev — APPROVED** [review]
/lgtm

**Pull request merged**
