### PR TITLE
[ART-8416] Add support for checking external packages

### PR DESCRIPTION
**Pull request by vfreex**
Enhance `doozer release:gen-payload` command to check external rpms
installed in RHCOS and group images.
    
Use following config to enable external package check for RHCOS and
group images.
    
```yaml
check_external_packages:
  - name: cri-o
    tag: rhaos-{MAJOR}.{MINOR}-rhel-{RHCOS_EL_MAJOR}-candidate
    condition: match
  - name: containernetworking-plugins
    tag: rhaos-{MAJOR}.{MINOR}-rhel-{RHCOS_EL_MAJOR}-candidate
    condition: match
  - name: NetworkManager
    tag: rhaos-{MAJOR}.{MINOR}-rhel-{RHCOS_EL_MAJOR}-candidate
    condition: greater_equal
```

### CODE REVIEW

**Comment by vfreex** [comment]
Example output:
```sh
doozer --data-path=https://github.com/vfreex/ocp-build-data.git --group=openshift-4.11 --assembly=4.11.46 --debug --images=openshift-enterprise-pod --rpms=openshift-clients release:gen-payload 
```
```yaml
  rhcos:
  - code: CONFLICTING_INHERITED_DEPENDENCY
    msg: Expected cri-o-1.24.6-4.rhaos4.11.git4bfe15a.el8 to be installed in RHCOS
      build 411.86.202307201000-0 but found cri-o-1.24.6-2.rhaos4.11.git4bfe15a.el8
    permitted: false
  - code: CONFLICTING_INHERITED_DEPENDENCY
    msg: Expected cri-o-1.24.6-4.rhaos4.11.git4bfe15a.el8 to be installed in RHCOS
      build 411.86.202307201000-0 but found cri-o-1.24.6-2.rhaos4.11.git4bfe15a.el8
    permitted: false
  - code: CONFLICTING_INHERITED_DEPENDENCY
    msg: Expected cri-o-1.24.6-4.rhaos4.11.git4bfe15a.el8 to be installed in RHCOS
      build 411.86.202307201000-0 but found cri-o-1.24.6-2.rhaos4.11.git4bfe15a.el8
    permitted: false
  - code: CONFLICTING_INHERITED_DEPENDENCY
    msg: Expected cri-o-1.24.6-4.rhaos4.11.git4bfe15a.el8 to be installed in RHCOS
      build 411.86.202307201000-0 but found cri-o-1.24.6-2.rhaos4.11.git4bfe15a.el8
    permitted: false
missing_image_builds: []
non_release_images: []
release_images:
- openshift-enterprise-pod
viable: false
```

**Comment by vfreex** [comment]
@thegreyd I've updated the PR to print a warning if rpm in tag is older than rhel. Regarding adding additional packages, it needs some discovery process to make the list more complete. I am ok with adding your proposed packages.

**Comment by thegreyd** [comment]
Makes sense! :+1:
/lgtm

**Pull request merged**
