### PR TITLE
[ART-7579] Pyartcd migration while preserving commits

### PR DESCRIPTION
**Pull request by ashwindasr**
Migrating pyartcd from `aos-cd-jobs` to `art-tools` repo. Preserving commits.

### CODE REVIEW

**Comment by ashwindasr** [comment]
Created a new repo, pyarcd by following this [doc](https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository) as recommended by @joepvd. Then merged the commits using this script:

```
mkdir working-dir

cd working-dir || exit

export FILTER_BRANCH_SQUELCH_WARNING=1

# pyartcd
git clone "https://github.com/ashwindasr/pyartcd"

# Pull data from the other git repos
git remote add --fetch pyartcd-temp working-dir/pyartcd/

# Merge the commit histories
git merge pyartcd-temp/master --allow-unrelated-histories

rm -rf working-dir
```

**Comment by ashwindasr** [comment]
/hold
After lgtm, merge, bump art-tools in aos-cd-jobs https://github.com/openshift-eng/aos-cd-jobs/pull/3925.
Scheduled for Friday ET morning.

**Review by sosiouxme — APPROVED** [review]

**Comment by ashwindasr** [comment]
Merging and bumping aos-cd-jobs pr https://github.com/openshift-eng/aos-cd-jobs/pull/3925

**Pull request merged**
