### PR TITLE
Re-apply Runtime refactoring with fixes for cloning public upstream repo

### PR DESCRIPTION
**Pull request by vfreex**
The 4th commit in this PR fixes an issue that the public upstream repo is not cloned if `get_public_upstream` returns a None public branch.

### CODE REVIEW

**Comment by joepvd** [comment]
/hold
Let's not merge this before 4.17 ECs are selected next week.

**Comment by vfreex** [comment]
PR rebased

**Comment by joepvd** [comment]
/lgtm
/approve

ready for unhold at your convenience :)

**Comment by vfreex** [comment]
@joepvd I just rebased again :)

**Pull request merged**
